### ISSUE TITLE
_forceTransfer is using private variables from the ERC20 contract

### ISSUE THREAD

**Issue by rafalklo** [AtomicCapital/atomic-dss#1]
The _forceTransfer prevents the contract from compiling because.

DeclarationError: Undeclared identifier.

`require(_value <= _balances[_from]);`

In order for this to work, the ERC20 contract would have to implement the _forceTransfer method, but it is not part of the standard. Any idea what is the best pattern for implementing this ?

**Comment by khaneight** [comment]
The base ERC20 contract must be overriden in order to implement the _forceTransfer method by either changing the scope of the _balances variable from private to internal, or by moving the internal _forceTransfer method into the ERC20 contract and adding `return super._forceTransfer(_from, _to, _value);` in the forceTransfer method inside the AtomicDSS contract. The production version implements both of these changes... hope this helps.
